name: Application Deployment

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd ~/api

            echo "
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DOCUMENTATION_URL=${{ secrets.DOCUMENTATION_URL }}
            REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}
            REFRESH_TOKEN_LIFETIME=86400
            ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
            ACCESS_TOKEN_LIFETIME=600
            SKIP_AUTH=false
            PORT=3000" > .env

            git fetch --all
            git reset --hard origin/master
            git status

            npm install
            npm run build
            npx prisma db push

            pm2 delete api || :
            pm2 start npm --name "api" -- run "start"
